### ISSUE TITLE
ip: dvi2rgb: Documentation requires update

### ISSUE THREAD

**Issue by sbobrowicz** [Digilent/vivado-library#1]
Documentation needs to be updated to reflect changes to the EDID and customization parameters. It should also be reved to v1.6 when this is corrected.

**Comment by elodg** [comment]
Hah. I did the same thing two days ago to make the core work with a GoPro. Created two edid variants, with 720p and 1080p preferred, and made it selectable. I also fixed a corner case where lock wouldn't be achieved. Haven't pushed it because the documentation wasn't ready. I will figure out how to best merge all of this.

**Comment by elodg** [comment]
Kept your EDIDs and described this feature in the documentation.
I did not check if your EDIDs still contain the same non-timing data as the table in the doc.

**Comment by sbobrowicz** [comment]
Ha, Oops... Looks like being on other sides of the ocean bites us again. Funny thing is I did this for exactly the same reason, GoPro compatibility. You don't have to be shy with the commits, we can fix errors or add documentation after the fact. 

The documentation still has a few errors, in one section you still reference the original .txt filename. Also I did change some other minor things in the EDID: The product IDs, monitor names, EDID version, I added another standard timing, and a few other things. I recommend downloading Phoenix EDID designer and using that to view the .dat files in the doc folder. We should also mention Phoenix, the .dat files, and the dat2txt.cpp program in the guide. If you want you can place the original .docx file in the doc folder so that way we can version control it too. I think that would be good practice with our product guides in these IP cores

FYI, I just tested the GoPro with this core on the ZYBO, and it won't transmit with the 1024 or 900 EDIDs... With the 1080 EDID it will transmit, but I was seeing a lot of corruption that I don't usually see with 1080p sources. The GoPro signals must be a little more shaky than typical. It works perfect with the 720p EDID. Considering this is a pretty common use case, we might want to consider setting 720p as the default (I have it at 900p now).

**Comment by elodg** [comment]
I use Deltacast E-EDID for EDID creation. Added the doc original to the repo, so go ahead and do the necessary edits.

**Comment by elodg** [comment]
Done in version 1.7 of the core.
