### ISSUE TITLE
MIPI CSI-2 and D-PHY IP Cores Missing

### ISSUE THREAD

**Issue by nelzey6** [Digilent/vivado-library#17]
Where are the Ip cores, which are needed for this proj: https://reference.digilentinc.com/reference/add-ons/pcam-5c/reference-manual#software_support

**Comment by elodg** [comment]
If you actually check out the demo project linked in that document, you will see that it includes the feature/d-phy branch of vivado-library as a submodule, which is where the two IPs are. This branch will be merged into master when the documentation gets more details and some known issues will be fixed.
