### ISSUE TITLE
usb2device sub-IP needs cleaning

### ISSUE THREAD

**Issue by sbobrowicz** [Digilent/vivado-library#19]
The source folders for the sub-IP used in the usb2device core use over 100 MB and account for over 2/3 of entire vivado-library repo's size. This is pretty serious, because it is contributing significant bloat to all the projects that use this repo as a submodule. 

Typically only the .xci and .xml need to be version controlled, though their may be some exceptions such as .coe's for memory IP.

**Comment by elodg** [comment]
Fixed in 42205401c6ce20ab8214d139d05e5c67fb6ea4b7
