### ISSUE TITLE
Adding vivado-library not working

### ISSUE THREAD

**Issue by ChristianChiarulli** [Digilent/vivado-library#21]
I have added the downloaded the vivado-library directory went to settings and added the path to vivado-library. My problem is under the Board tab there is not connections including the ja, jb, etc.. nor anything for HDMI.

**Comment by elodg** [comment]
Not a bug. You should be looking for the vivado-boards repo: https://reference.digilentinc.com/reference/software/vivado/board-files#installation
For support go to the forum.
