### ISSUE TITLE
INTC does not name a type in PmodGPS example

### ISSUE THREAD

**Issue by mahdiunh** [Digilent/vivado-library#22]
Hello,
I am trying to run the PmodGPS example code, but after copying the code into my main.c file, I see multiple definitions missing:

1 - 'INTC' does not name a type ---- line 69
2 - 'XPAR_INTC_0_DEVICE_ID' was not declared in this scope ---- line 86
3 - 'XPAR_INTC_0_PMODGPS_0_VEC_ID' was not declared in this scope ---- line 87

Based on atangzwj comments, this example has beed tested on Vivado 2017.4 recently. I made sure that the related header file ("xintc.h") exists in the SDK directory, but whatever the problem is, it seems these type and character are not defined properly. Is there anyone who can help me with this?
Best,
Mahdi

**Comment by elodg** [comment]
These are defined in the "xparameters.h" include file generated by the BSP referenced by the application. Did you forget to copy the includes?

**Comment by mahdiunh** [comment]
Thanks for your response. After scrolling up and down in the code for a few hours, I realized I had not enabled the interrupt controller in my microblaze diagram. After doing that, it seems to be running with no issues. Great job.
