### ISSUE TITLE
Drivers for Pmods in SDK 2018.1 / Vivado 18.1 missing

### ISSUE THREAD

**Issue by quicktom** [Digilent/vivado-library#29]
Hello, I use Vivado 18.1 and the vivado-library. 
If I create a block design for the zybo z20 with several pmods.
Problem: in the SDK the pmods drivers from this library do not appear in the bsp.
The hdf  shows all Pmods but the drivers are wrong.

Thanks in advance
Thomas

![image](https://user-images.githubusercontent.com/21122850/40970373-b0bafdca-68ba-11e8-8e64-6115fe0ba5d3.png)

**Comment by elodg** [comment]
Check with the latest release first: https://github.com/Digilent/vivado-library/releases
Validation for 2017.4 is ongoing.
Please report back if behavior is different than in 2018.1.

**Comment by quicktom** [comment]
Hi elodg,

thanks for response.

I did it so already.  Using the latest release of vivado-library against 2017.4  works. 

I created the same block design from scratch in 18.1 and it fails as above
except PmodGPIO in my case.

Regards

**Comment by elodg** [comment]
I noticed the buggy behavior of Vivado not exporting all drivers of custom IP to the hand-off file. A workaround is to add vivado-library as a repository in SDK, so that BSP can pick up the relevant drivers.
