### ISSUE TITLE
PmodRTCC.c - RTCC_setSec() - Minor Bug - Quick Fix

### ISSUE THREAD

**Issue by zahedim** [Digilent/vivado-library#30]
Hi,

https://github.com/Digilent/vivado-library/blob/master/ip/Pmods/PmodRTCC_v1_0/drivers/PmodRTCC_v1_0/src/PmodRTCC.c

line 767: u8 rgbSec[0]; 

should be: u8 rgbSec[2];

Greetings from Austria

**Comment by elodg** [comment]
Obviously, thanks!
