### ISSUE TITLE
Vivado 2018.2 Integration

### ISSUE THREAD

**Issue by jackfrye** [Digilent/vivado-library#32]
1.) I have tried adding the repos to Vivado 2018.2 but they do not seem to be recognized as IP. 
2.) All the IP from this repo when referenced in the Zybo-hdmi-in and Zybo-hdmi-out projects are locked.

I cannot figure out how to upgrade/regenerate them since they do not come with their own Vivado projects.

**Comment by fake-name** [comment]
I'm seeing this too.

**Comment by fake-name** [comment]
In my case, it wound up being me adding the libraries in the wrong place. I was adding them to the project template library listing, rather then the active project library listing. 

Presumably, if I created a new project it would have worked as-is.

Derp.

**Comment by elodg** [comment]
You are mixing two subjects in a single issue. One is version support, the other is FPGA family support. For Zynq UltraScale+ I created a branch that will be eventually merged back into master: https://github.com/Digilent/vivado-library/tree/feature/zuplus_support
