### ISSUE TITLE
Pmod NAV example code errors, and driver improvement

### ISSUE THREAD

**Issue by eyip002** [Digilent/vivado-library#33]
# Conversion Errors
The conversion between meters and feet have been inverted in the PmodNav example code.

## Feet to Meters
https://github.com/Digilent/vivado-library/blob/69dbafb23c48019dfe731bb45aa0ac2350fb0ddc/ip/Pmods/PmodNAV_v1_0/drivers/PmodNAV_v1_0/examples/main.c#L363-L365

Should be corrected to the following:

```c
float NavDemo_ConvFeetToMeters(float feet) {  
	return feet * 0.3048;  
}
```

## Meters to Feet

https://github.com/Digilent/vivado-library/blob/69dbafb23c48019dfe731bb45aa0ac2350fb0ddc/ip/Pmods/PmodNAV_v1_0/drivers/PmodNAV_v1_0/examples/main.c#L380-L382

Should be corrected to the following:

```c
float NavDemo_ConvMetersToFeet(float meters) {
	return meters * 3.28084;
}
```

# Premature Rounding of Pressure Reading

The calculation of hPa uses integer division, thus, the decimal part of the hPa is lost:

https://github.com/Digilent/vivado-library/blob/8379585358aa4ec89e77c871bbb4f58812098400/ip/Pmods/PmodNAV_v1_0/drivers/PmodNAV_v1_0/src/PmodNAV.c#L1932

The decimal part can be retained by casting `dataRawFull` to a `float`:

```c
InstancePtr->hPa = ((float)dataRawFull / 4096);
```

**Comment by elodg** [comment]
Could you post a pull-request with these changes? I believe the third item requires more work as dataRawFull is wrongly declared as unsigned, so the result won't be correctly sign extended.

**Comment by artvvb** [comment]
Resolved in https://github.com/Digilent/vivado-library/commit/d53eaba93a821784fdd7f94cf6e5ea8f8d8a8933
