### ISSUE TITLE
PmodOLEDrgb

### ISSUE THREAD

**Issue by profroyk** [Digilent/vivado-library#34]
The PmodOLEDrgb fails to build when Generate Out of Context IP is started.   I get these fatal errors:

![image](https://user-images.githubusercontent.com/3301287/55675291-5ad77b80-5875-11e9-8c0b-62a397070088.png)

I have tried this in Vivado 2018.3 under Windows and Vivado 2018.2 under Linux and got the same result.  I have shortened the path as much as is reasonable (given the Windows path size limit) and I doubt that's the issue since I was able to build an identical design with the previous release and it synthesized and implemented correctly.

The board type is Nexys4 DDR but I am not using the board package.  Instead I added the Digilient IP repository to my project and added the PmodOLEDrgb using the Add IP command and specified the FPGA type in the project settings window.

Thanks
Roy

**Comment by anamariabalas** [comment]
Fixed in 3b1cf51cdcd389f2ecdaf1d57c4967e6af8b240d.
Also https://github.com/Digilent/vivado-library/releases/tag/v2018.2-2
