### ISSUE TITLE
Digilent PMODsf3 porting to gnu toolchain

### ISSUE THREAD

**Issue by jasonlo0509** [Digilent/vivado-library#36]
Hello,

I want to use Digilent PMODSF3 with self-designed risc-v core & SoC, therefore I need a version of PMODSF3 driver & tests that can be runned on gnu toolchain but not on Xilinx SDK.
Could you please provide me some instruction on how to port the api?

Thank you very much!
Yun-Chen Lo, Tsing Hua University, Taiwan

**Comment by elodg** [comment]
This is not an issue with the vivado-library, hence the closure. All IPs here assume Vivado toolset and Xilinx SoC.
The SF3 driver relies on a Quad SPI controller for physical interface implementation. If you wish to port it to another SoC, replace the QSPI calls with your platform's own.

You may post the question on https://forum.digilentinc.com/.
