### ISSUE TITLE
ip: rgb2dvi: Bad constraints when using external serial clock

### ISSUE THREAD

**Issue by sbobrowicz** [Digilent/vivado-library#4]
When using an externally generated serial clock the -source constraint added by the core seems to assume that serial clock is directly generated by the pixel clock, which doesn't make much sense (if anything it would be vice versa via a BUFR, but that is not always the case either). This causes several critical warnings and seems to confuse the clocking analysis.

Unless this constraint is serving some purpose, I think it should be removed. The clock generation should be handled by the upstream core that actually generates the clocks.

**Comment by elodg** [comment]
Fixed by removing clock constraints and relying on auto-derived ones.
