### ISSUE TITLE
DVI2RGB IP reports error during implementation

### ISSUE THREAD

**Issue by zhewang1996** [Digilent/vivado-library#47]
Sorry to bother you again.I have already constrained the clock <create_clock -period 13.468 [get_ports TMDS_Clk_p]>(720P 74.25Mhz),but there was an error in the implementation:
--------------------------------------
[Place 30-575] Sub-optimal placement for a clock-capable IO pin and MMCM pair. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
< set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets u_dvi2rgb_0/U0/TMDS_ClockingX/ CLK_IN_hdmi_clk] >
----------------------------------------
So I use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file,the error disappeared, but the ILA was not found,I can't debug.By the way,the type of FPGA I use is xc7z020clg400

**Comment by elodg** [comment]
These are not really bugs in out vivado-library. Please post inquiries such as this on our forum so others can benefit from the answer: https://forum.digilentinc.com/forum/4-fpga/.
In short you must make sure the CLK_IN_hdmi_clk pin is a clock-capable pin on your board AND there is a free MMCM in the clock region that pin is in. Either your pin is not clock-capable or there is already an MMCM placed there by other logic.

**Comment by zhewang1996** [comment]
Thank you very much!
