### ISSUE TITLE
Error: Black box instances on ZMOD ADC IP (ZmodScopeController)

### ISSUE THREAD

**Issue by ramadhanafif** [Digilent/vivado-library#59]
Error when running implementation with ZmodScopeController IP for ZMOD ADC 1410.
I am using Eclypse Z7 board.

![image](https://user-images.githubusercontent.com/31378187/141099909-f5044602-cf74-452a-ba89-dd4822b9de0c.png)

To reproduce: 
1. Clone lowlevelLPF demo and its submodules for Eclypse Z7 [here](https://github.com/Digilent/Eclypse-Z7-HW/tree/lowlevel_lpf/master)
2. Run the tcl script in directory LowLevelLPF/scripts/digilent_vivado_checkout.tcl
3. Re-generate block design (global)
![image](https://user-images.githubusercontent.com/31378187/141100451-19999aad-5bf0-4414-a39f-436dcd5502da.png)
4.  Run synthesis and implementation. The error is happened at implementation.

**Comment by artvvb** [comment]
Hi ramadhanafif,

How did you clone the repository? Through command line, the Github site, or through some GUI. The error seems to indicate that not all of the sources for the Scope controller IP have been picked up from the submodule, or are somehow incompatible with the Vivado installation being used.

It's likely not relevant, but what version of Vivado are you using?

Thanks,
Arthur

**Comment by ramadhanafif** [comment]
Since this is just library of IPs, I download it through GitHub site. 

As what you just suggested, I cloned the IPs through command line with 
`git clone https://github.com/Digilent/vivado-library --recursive`
Then I created a new project to test the Zmod Scope IP, but now I encountered another problem 
![image](https://user-images.githubusercontent.com/31378187/141363960-49a729bf-b3ce-4dfe-b828-3586dea8aa8f.png)
It said that port ADC_SamplingClk is not connected to valid clock source.

I'm using Vivado 2019.1 on Windows11

**Comment by artvvb** [comment]
I'd recommend downloading the ZIP release of the low-pass filter project here: https://github.com/Digilent/Eclypse-Z7/releases/tag/lowlevel_lpf/2019.1-2. It contains an XPR which can be opened in Vivado and the proper versions of the IP.

**Comment by ramadhanafif** [comment]
Okay, will try that one

**Comment by ramadhanafif** [comment]
Sorry, the problem still persists.
![image](https://user-images.githubusercontent.com/31378187/141365588-8c320373-1ea1-4117-b476-612c41de4b47.png)

Steps to generate the problem is the same as [my first post](https://github.com/Digilent/vivado-library/issues/59#issue-1049677129).

**Comment by ramadhanafif** [comment]
Have you tried the project? And if you already did, do you find any errors?

**Comment by artvvb** [comment]
Yes, both myself and a colleague have run through it, downloading the sources by running the following command, to pick up all of the submodules and the root repo on the demo branch:

git clone --recursive https://github.com/Digilent/Eclypse-Z7 -b lowlevel_lpf/master

I successfully generate a bitstream with some warnings and one critical warning about the FIR filter being packaged with a board part when the project doesn't have one set.

What are the critical warnings appearing in your project?

**Comment by ramadhanafif** [comment]
Thank you very much to you and your colleague for assistance and your response. 

> I successfully generate a bitstream with some warnings and one critical warning about the FIR filter being packaged with a board part when the project doesn't have one set.

Just to be clear, I also successfully generate bitstream when I just: clone, run checkout script, and then run synthesis-implementation-generate bitstream. The problem lies when other blocks are added and I re-generate output products for the block design.

Since I wishes to modify the demo by reading the ADC data in petalinux, therefore I put a Zynq PS block and other necessary blocks in IP integrator (block design). Because I add some new blocks in the block design, therefore I need to regenerate the output products.

If I regenerate the output products, an error about "black box instances" in Zmod Scope IP always shows up in implementation process. I hope this clarify my question. 

To reproduce this error, you don't need to add other blocks. I have checked that the problem always appear when output products is re-generated. Detailed steps on how you could reproduce this problem is in [my first post](https://github.com/Digilent/vivado-library/issues/59#issue-1049677129)

**Comment by ramadhanafif** [comment]
Hello. To solve this problem, please use ADC IPs from here https://github.com/Digilent/vivado-library/.
The Low Level LPF demo by default uses its own IP, which separate from Vivado global IP. In this case, you will encounter a duplicates IP, therefore you must manually choose in the IP settings which IP you use.
