### ISSUE TITLE
Pmod OLEDrgb documentation typo

### ISSUE THREAD

**Issue by jzeiselmusic** [Digilent/vivado-library#71]
Just a quick note that in the reference manual [https://digilent.com/reference/pmod/pmodoledrgb/reference-manual?redirect=1](url) for Pmod OLEDrgb in step number (27) for the power on sequence, it seems to me that the SPI command to be sent should say SpiWrite(0x2E) instead of SpiWrite(0x25E).

**Comment by artvvb** [comment]
Fixed, thanks!

**Comment by jzeiselmusic** [comment]
I will also add that, having just gone through all the steps in the above link with a bare-metal fpga design, you may want to change the command SpiWrite(0xA4) in step number (12) to SpiWrite(0xA5) - simply because A4 starts the board in "normal" display mode which gives no indication that the board has actually turned on. If a user wants to do a power-on sequence and know that it is working, the A5 command starts the board with a white screen so that there is a clear difference between on and off. User can then change it later if they want a black background. Just my 2 cents
